services:
  builder:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: pve-iso-builder
    volumes:
      # Maps current folder to /data so the container can read answer.toml and write the ISO
      - .:/data
    environment:
      - OUTPUT_UID=${UID:-1000}
      - OUTPUT_GID=${GID:-1000}
      - PROXMOX_PASS=${PROXMOX_PASS}
      - PROXMOX_HOST=${PROXMOX_HOST}
      - PROXMOX_MAC=${PROXMOX_MAC}
      - GATEWAY=${GATEWAY}

